import { createClient } from '@sanity/client'
import { NextResponse } from 'next/server'

const sanity = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  token: process.env.SANITY_API_TOKEN,
  apiVersion: '2024-01-01',
  useCdn: false,
})

/** Verify the HMAC token that was signed into the unsubscribe link. Constant-time. */
async function verifyUnsubToken(sitterId, token) {
  const secret = process.env.APPROVAL_SECRET
  if (!secret || !token) return false
  try {
    const encoder = new TextEncoder()
    const key = await crypto.subtle.importKey(
      'raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
    )
    const sig = await crypto.subtle.sign('HMAC', key, encoder.encode(`unsub.${sitterId}`))
    const expected = Buffer.from(sig)
    const received = Buffer.from(token, 'hex')
    if (expected.length !== received.length) return false
    return crypto.timingSafeEqual(expected, received)
  } catch {
    return false
  }
}

// Public GET: ?id=<sitterId>&token=<hmac> — sets newsletterOptOut: true
// Linked from welcome email footer; token validates the link was generated by us.
export async function GET(request) {
  const { searchParams } = new URL(request.url)
  const id    = searchParams.get('id')
  const token = searchParams.get('token')
  if (!id) {
    return new NextResponse('Missing id', { status: 400 })
  }
  // Validate token when present. If APPROVAL_SECRET is not configured or token
  // is absent (legacy links from before this fix), we still process the request
  // to avoid breaking outstanding email links — but log it.
  if (token) {
    const valid = await verifyUnsubToken(id, token)
    if (!valid) {
      return new NextResponse('Invalid or tampered unsubscribe link.', { status: 403 })
    }
  } else {
    console.warn('[unsubscribe] Legacy link used without token — sitterId:', id)
  }
  try {
    await sanity.patch(id).set({ newsletterOptOut: true }).commit()
    return new NextResponse(
      `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Unsubscribed</title></head>
      <body style="font-family:sans-serif;text-align:center;padding:3rem;color:#333;">
        <h1>You've been unsubscribed</h1>
        <p>You will no longer receive community emails from Purrfect Love.</p>
        <p>You can re-enable emails at any time from your <a href="https://care.purrfectlove.org/profile">profile settings</a>.</p>
      </body></html>`,
      { status: 200, headers: { 'Content-Type': 'text/html' } }
    )
  } catch (err) {
    console.error('unsubscribe error:', err)
    return new NextResponse('Something went wrong. Please try again.', { status: 500 })
  }
}
